#include "keymap_common.h"

const uint8_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    KEYMAP_ANSI(
        ESC ,2   ,3   ,4   ,5   ,6   ,TRNS,7   ,8   ,9   ,0   ,1   ,BSPC,\
        TAB ,Q   ,W   ,E   ,R   ,T   ,Y   ,U   ,I   ,O   ,P   ,LBRC,RBRC,\
        LCTL,A   ,S   ,D   ,F   ,G   ,TRNS,H   ,J   ,K   ,L   ,SCLN,RCTL,\
        MINS,QUOT,Z   ,X   ,C   ,V   ,B   ,N   ,M   ,COMM,DOT ,SLSH,EQL ,\
        LSFT,TRNS,GRV ,LGUI,TRNS,FN0 ,FN1 ,FN2 ,TRNS,RALT,BSLS,TRNS,RSFT),
    KEYMAP_ANSI(
        F1  ,F2  ,F3  ,F4  ,F5  ,F6  ,TRNS,F7  ,F8  ,F9  ,F10 ,F11 ,F12 ,\
        APP ,TRNS,TRNS,TRNS,MS_U,TRNS,TRNS,TRNS,WH_U,TRNS,TRNS,TRNS,TRNS,\
        TRNS,TRNS,MS_L,MS_D,MS_R,TRNS,TRNS,TRNS,WH_L,WH_D,WH_R,TRNS,TRNS,\
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,\
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,DEL ,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS),
    KEYMAP_ANSI(
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,\
        TRNS,1   ,2   ,3   ,4   ,5   ,6   ,7   ,8   ,9   ,0   ,TRNS,TRNS,\
        TRNS,TRNS,TRNS,TRNS,TRNS,VOLD,TRNS,VOLU,TRNS,TRNS,TRNS,TRNS,TRNS,\
        CAPS,F1  ,F2  ,F3  ,F4  ,F5  ,F6  ,F7  ,F8  ,F9  ,F10 ,F11 ,F12 ,\
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS),
    KEYMAP_ANSI(
        F1  ,F2  ,F3  ,F4  ,F5  ,F6  ,TRNS,F7  ,F8  ,F9  ,F10 ,F11 ,F12 ,\
        APP ,TRNS,TRNS,TRNS,PGUP,HOME,TRNS,TRNS,UP  ,TRNS,TRNS,TRNS,TRNS,\
        TRNS,TRNS,HOME,PGDN,END ,TRNS,TRNS,TRNS,LEFT,DOWN,RGHT,TRNS,TRNS,\
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,\
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,BSPC,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS),
};

const action_t PROGMEM fn_actions[] = {
    [0] = ACTION_LAYER_TAP_KEY(1, KC_ENT),
    [1] = ACTION_LAYER_TAP_KEY(2, KC_ESC),
    [2] = ACTION_LAYER_TAP_KEY(3, KC_SPACE),
};
