#include "keymap_common.h"

const uint8_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    KEYMAP_ANSI(
        ESC ,2   ,3   ,4   ,5   ,6   ,TRNS,7   ,8   ,9   ,0   ,1   ,BSPC,\
        TAB ,Q   ,W   ,E   ,R   ,T   ,Y   ,U   ,I   ,O   ,P   ,LBRC,RBRC,\
        LCTL,A   ,S   ,D   ,F   ,G   ,TRNS,H   ,J   ,K   ,L   ,SCLN,RCTL,\
        MINS,QUOT,Z   ,X   ,C   ,V   ,B   ,N   ,M   ,COMM,DOT ,SLSH,EQL ,\
        LSFT,TRNS,GRV ,LGUI,TRNS,FN0 ,BTN3,FN1 ,TRNS,RALT,BSLS,TRNS,RSFT),
    KEYMAP_ANSI(
        F1  ,F2  ,F3  ,F4  ,F5  ,F6  ,TRNS,F7  ,F8  ,F9  ,F10 ,F11 ,F12 ,\
        CAPS,TRNS,TRNS,TRNS,UP  ,WH_U,VOLU,WH_U,PGUP,TRNS,TRNS,TRNS,DEL ,\
        TRNS,TRNS,LEFT,DOWN,RGHT,WH_D,TRNS,WH_D,HOME,PGDN,END ,TRNS,TRNS,\
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,VOLD,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,\
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,APP ,TAB ,TRNS,TRNS,TRNS,TRNS,TRNS),
    KEYMAP_ANSI(
        F1  ,F2  ,F3  ,F4  ,F5  ,F6  ,TRNS,F7  ,F8  ,F9  ,F10 ,F11 ,F12 ,\
        CAPS,TRNS,TRNS,TRNS,PGUP,WH_U,VOLU,WH_U,UP  ,TRNS,TRNS,TRNS,DEL ,\
        TRNS,TRNS,HOME,PGDN,END ,WH_D,TRNS,WH_D,LEFT,DOWN,RGHT,TRNS,TRNS,\
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,VOLD,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,\
        TRNS,TRNS,TRNS,TRNS,TRNS,TAB ,BTN2,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS),
};

const action_t PROGMEM fn_actions[] = {
    [0] = ACTION_LAYER_TAP_KEY(1, KC_ENT),
    [1] = ACTION_LAYER_TAP_KEY(2, KC_SPACE),
};
