#include "keymap_common.h"

const uint8_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    KEYMAP_ANSI(
        ESC ,2   ,3   ,4   ,5   ,6   ,TRNS,7   ,8   ,9   ,0   ,1   ,BSPC,\
        TAB ,Q   ,W   ,E   ,R   ,T   ,Y   ,U   ,I   ,O   ,P   ,LBRC,RBRC,\
        LCTL,A   ,S   ,D   ,F   ,G   ,TRNS,H   ,J   ,K   ,L   ,SCLN,RALT,\
        MINS,EQL ,Z   ,X   ,C   ,V   ,B   ,N   ,M   ,COMM,DOT ,SLSH,BSLS,\
        LSFT,GRV ,LGUI,TRNS,FN0 ,TRNS,BTN3,TRNS,FN1 ,TRNS,RGUI,QUOT,RSFT),
    KEYMAP_ANSI(
        CAPS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,DEL ,\
        TRNS,TRNS,TRNS,TRNS,PGUP,WH_U,VOLU,WH_U,UP  ,TRNS,TRNS,TRNS,TRNS,\
        TRNS,TRNS,HOME,PGDN,END ,WH_D,TRNS,WH_D,LEFT,DOWN,RGHT,TRNS,TRNS,\
        F1  ,F2  ,F3  ,F4  ,F5  ,F6  ,VOLD,F7  ,F8  ,F9  ,F10 ,F11 ,F12 ,\
        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,APP ,TRNS,SPC ,TRNS,TRNS,TRNS,TRNS ),
    KEYMAP_ANSI(
        CAPS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,DEL ,\
        TRNS,TRNS,TRNS,TRNS,PGUP,WH_U,VOLU,WH_U,UP  ,TRNS,TRNS,TRNS,TRNS,\
        TRNS,TRNS,HOME,PGDN,END ,WH_D,TRNS,WH_D,LEFT,DOWN,RGHT,TRNS,TRNS,\
        F1  ,F2  ,F3  ,F4  ,F5  ,F6  ,VOLD,F7  ,F8  ,F9  ,F10 ,F11 ,F12 ,\
        TRNS,TRNS,TRNS,TRNS,ENT ,TRNS,BTN2,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS),
};

const action_t PROGMEM fn_actions[] = {
    [0] = ACTION_LAYER_TAP_KEY(1, KC_ENT),
    [1] = ACTION_LAYER_TAP_KEY(2, KC_SPACE),
};
